### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by HitzeD**
# Description

Dashboard has finally arrived! It is filled with fun stuff ranging from a nice user bar with images and links, A carousel built by @krislidimo at the bottom of the page. 

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works AND the tests pass

### CODE REVIEW

**Comment by HitzeD** [comment]
https://5d41de1bda778e000a99d50f--mympydreamers-staging.netlify.com

**Comment by NickStrick** [comment]
looks like the search page, and project page routes arent working with this

**Comment by HitzeD** [comment]
running the live preview link, it works on my machine.

**Comment by NickStrick** [comment]
https://5d41de1bda778e000a99d50f--mympydreamers-staging.netlify.com/market/1

this endpoint doesnt work for me

**Comment by HitzeD** [comment]
https://5d41efe2da778e000a99de91--mympydreamers-staging.netlify.com/ @NickStrick 

Here is a fix!

**Comment by NickStrick** [comment]
awesome, one last thing, the '/market' doesnt work if you try to go there from the dashboard

**Comment by HitzeD** [comment]
hmm, I'll take a look at that as well!

**Comment by HitzeD** [comment]
https://5d41f627bd9df1000851b2f1--mympydreamers-staging.netlify.com/dashboard

@NickStrick I believe we have final fix!

**Comment by NickStrick** [comment]
yeah i would fix that journal path before pushing this, just really need the app to be functional completely before it goes to master

**Pull request merged**
